In [ ]:
import numpy as np

# Create a 1xN dimensional vector
vector = np.array([1, 2, 3, 4, 5])

# Compute the mean
mean = np.mean(vector)

# Compute the variance
variance = np.var(vector)

print(f"Mean: {mean}")
print(f"Variance: {variance}")


Mean: 3.0
Variance: 2.0


In [ ]:
import numpy as np

# Create two 1xM dimensional vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 4, 6, 8, 10])

# Compute the covariance
covariance = np.cov(vector1, vector2)[0, 1]

print(f"Covariance: {covariance}")


Covariance: 5.0


In [ ]:
import numpy as np

# Create two 1xN dimensional vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 4, 6, 8, 10])

# Compute the correlation
correlation = np.corrcoef(vector1, vector2)[0, 1]

print(f"Correlation: {correlation}")


Correlation: 0.9999999999999999


In [ ]:
import numpy as np

# Create an MxN dimensional matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the covariance matrix
cov_matrix = np.cov(matrix, rowvar=False)

# Compute the correlation matrix
corr_matrix = np.corrcoef(matrix, rowvar=False)

print(f"Covariance Matrix:\n{cov_matrix}")
print(f"Correlation Matrix:\n{corr_matrix}")


Covariance Matrix:
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
